# Generated by Django 5.2.1 on 2025-05-13 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название пункта меню')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='URL или named URL')),
                ('named_url', models.CharField(blank=True, help_text='Именованный URL из urls.py', max_length=255, verbose_name='Named URL')),
                ('menu_name', models.CharField(help_text='Название меню, к которому относится этот пункт', max_length=50, verbose_name='Название меню')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tree_menu.menuitem', verbose_name='Родительский пункт')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
                'ordering': ['order'],
            },
        ),
    ]
